apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: dummy
  namespace: default
spec:
  backendType: vault
  kvVersion: 1
  data:
    - name: name
      key: secret/fleet/dummy
      property: name
