apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8SRegistryLimit
metadata:
  name: registry-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
    - default
